### ISSUE TITLE
Error message during install via nabu casa

### ISSUE THREAD

**Issue by confucius78** [cgtobi/netatmo_custom#3]
HA version: 2022.02.9

Issue:
Log error when setting up the integration. Tested when setting up therough nabu casa, but I will re-test local install and confirm behaviour.

Log:
`2022-03-04 11:36:56 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Configuration.yaml for netatmo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/netatmo/__init__.py", line 218, in async_setup_entry
    cloud.async_listen_connection_change(hass, manage_cloudhook)
AttributeError: module 'homeassistant.components.cloud' has no attribute 'async_listen_connection_change'`

**Comment by cgtobi** [comment]
This is fixed when upgrading HA to 2022.3.
